name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Prova-per-action
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: RR/Documenti Interni/Studio di Fattibilità/studioFattibilita.tex

      - name: PDF
        uses: actions/upload-artifact@v2
        with:
          path: RR/Documenti Interni/Studio di Fattibilità/studioFattibilita.pdf

